> [!tip]
> **`throw`** 문은 사용자 정의 예외를 발생(throw)할 수 있습니다. 예외가 발생하면 현재 함수의 실행이 중지되고 (`throw` 이후의 명령문은 실행되지 않습니다.), 제어 흐름은 콜스택의 첫 번째 `catch`블록으로 전달됩니다. 호출자 함수 사이에 `catch` 블록이 없으면 프로그램이 종료됩니다.

```javascript
// 문법
throw expression;

// 구문
throw "Error2"; // 문자열 값을 가지는 예외가 발생합니다.
throw 42; // 42 값을 가진 예외가 발생합니다.
throw true; // true 값을 가지는 예외가 발생합니다.
```
